### ISSUE TITLE
Java path in Windows registry

### ISSUE THREAD

**Issue by kolAflash** [alexkasko/openjdk-unofficial-builds#7]
Can you make the windows installer add this registry stuff with the correct OpenJDK installation-path?

===BEGIN===
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment\1.7]
"JavaHome"="C:\Programme\Java\OpenJDK7_u6\jre"

===END===

It's needed by some (maybe all) Window Software to find Java. Until now, I've successfully tested it with "openjdk-1.7.0-u6-unofficial-b24-windows-i586.zip" and this software:
- LibreOffice ( https://www.libreoffice.org/ ) database module (which requires Java)
- TV-Browser ( http://www.tvbrowser.org/ )

Thanks!
kolAflash

**Comment by m3hdiii** [comment]
Hello 
As I noticed Launch4J works with the key **CurrentVersion** which is located in windows registry :
`HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment`

for example if **CurrentVersion=1.8.0_05** the app try to look at a folder key **1.8.0_05** underneath of Java Runtime Environment so the path to look up is:
`HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment\1.8.0_05`

Then from there you should have the JDK OR JRE path with **JavaHome** Key EX:
[JavaHome]=[C:\\Program Files\\java\\jdk8-u5]

Then it can run properly.

Here is exported registry myfile.reg content. **TAKE NOTE YOU SHOULD CHANGE THE VALUES TO YOUR VERSION AND YOUR PATH :**

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft]

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment]
"CurrentVersion"="1.8.0_05"

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment\1.8.0_05]
"JavaHome"="C:\\Program Files\\java\\jdk8-u5"

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Prefs]
```

**Comment by m3hdiii** [comment]
I think this part needs some improvements, here are my suggestions:

- Launch4J was not able to find the **Java Runtime Environment** registry key, it looks for JAVA_HOME or JRE_HOME environment variables and try to run the app if either of them are available
- If Launch4J was not able to find any of the above, it asks from the user to enter the path or browse to the Java_HOME directory

I consider this as a bug because the app is very dependent to **one way** of looking for existing JRE and if in any case that way breaks, the app itself will break too
